{% set version = '0.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyposterior
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyposterior_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidyposterior_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyposterior/tidyposterior_{{ version }}.tar.gz
  sha256: 3a8b32607ba38771992e17f16a9ea188e8d95386fe1363bcf4585ae64756abe9

build:
  merge_build_host: True  # [win]
  number: 1000
  # r-stanarm not available on win
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rsample >=0.0.2
    - r-tidyr >=0.7.1
    - r-dplyr
    - r-rstanarm >=2.15.3
    - r-rlang
    - r-purrr
    - r-tibble
    - r-generics
    - r-ggplot2
  run:
    - r-base
    - r-rsample >=0.0.2
    - r-tidyr >=0.7.1
    - r-dplyr
    - r-rstanarm >=2.15.3
    - r-rlang
    - r-purrr
    - r-tibble
    - r-generics
    - r-ggplot2

test:
  commands:
    - $R -e "library('tidyposterior')"           # [not win]
    - "\"%R%\" -e \"library('tidyposterior')\""  # [win]

about:
  home: https://topepo.github.io/tidyposterior
  license: GPL-2
  summary: 'Bayesian analysis used here to answer the question: "when looking at resampling results,
    are the differences between models ''real''?" To answer this, a model can be created
    were the performance statistic is the resampling statistics (e.g. accuracy or RMSE).
    These values are explained by the model types. In doing this, we can get parameter
    estimates for each model''s affect on performance and make statistical (and practical)
    comparisons between models. The methods included here are similar to Benavoli et
    al (2017) <http://jmlr.org/papers/v18/16-305.html>.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
