{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyposterior
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyposterior_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyposterior/tidyposterior_{{ version }}.tar.gz
  sha256: 5071e3ba22305455d52bc343fdcce63aca29acf568666be09dcabc2c353126c0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >1.0.0
    - r-generics
    - r-ggplot2
    - r-purrr
    - r-rlang
    - r-rsample >=0.0.2
    - r-rstanarm >=2.21.1
    - r-tibble
    - r-tidyr >=0.7.1
    - r-tune >=0.1.2.9000
    - r-vctrs >=0.3.0
    - r-workflowsets
  run:
    - r-base
    - r-dplyr >1.0.0
    - r-generics
    - r-ggplot2
    - r-purrr
    - r-rlang
    - r-rsample >=0.0.2
    - r-rstanarm >=2.21.1
    - r-tibble
    - r-tidyr >=0.7.1
    - r-tune >=0.1.2.9000
    - r-vctrs >=0.3.0
    - r-workflowsets

test:
  commands:
    - $R -e "library('tidyposterior')"           # [not win]
    - "\"%R%\" -e \"library('tidyposterior')\""  # [win]

about:
  home: https://tidymodels.github.io/tidyposterior
  license: MIT
  summary: "Bayesian analysis used here to answer the question: \"when looking at resampling results, are the differences between models 'real'?\" To answer this, a model can be created were the performance statistic is the resampling statistics (e.g. accuracy or RMSE). These values are explained by the model types. In doing\
    \ this, we can get parameter estimates for each model's affect on performance and make statistical (and practical) comparisons between models. The methods included here are similar to Benavoli et al (2017) <http://jmlr.org/papers/v18/16-305.html>."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidyposterior
# Version: 0.0.2
# Title: Bayesian Analysis to Compare Models using Resampling Statistics
# Description: Bayesian analysis used here to answer the question: "when looking at resampling results, are the differences between models 'real'?" To answer this, a model can be created were the performance statistic is the resampling statistics (e.g. accuracy or RMSE). These values are explained by the model types. In doing this, we can get parameter estimates for each model's affect on performance and make statistical (and practical) comparisons between models. The methods included here are similar to Benavoli et al (2017) <http://jmlr.org/papers/v18/16-305.html>.
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph"))
# License: GPL-2
# URL: https://tidymodels.github.io/tidyposterior
# BugReports: https://github.com/tidymodels/tidyposterior/issues
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.0.9000
# Depends: R (>= 2.10)
# Imports: rsample (>= 0.0.2), tidyr (>= 0.7.1), dplyr, rstanarm (>= 2.15.3), rlang, utils, purrr, tibble, generics, ggplot2,
# Suggests: knitr, testthat, covr
# NeedsCompilation: no
# Packaged: 2018-11-15 19:50:59 UTC; max
# Author: Max Kuhn [aut, cre], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-11-15 20:20:03 UTC
