travis:
  secure:
    BINSTAR_TOKEN: F0jMF2u60Xbugoz8/V8weYxolhot4cuw/ebhbQFUXpiN6rQMjFWTCWEnxXUSAiBA9rbbN7RlrCx+yNgdFT2wxesYJKr5w/rmWMijd1EJIqOMGWPOidrY0KnTKHoc1sqhvjrrQm+IdHKlQWWU2J8CXpZD/WDkZk+UuNPOafVkRE78YdKwF4dxfucK05j//X5J8UGJKuyhNrJTeihTno9Tcszjiks9gJYfF7cQe/7Mu7jVSE8yMYttXQc2q7PiWjzseI7DVeWs/VomBw9Qqh1QD/gMZ2eJV/XrL4G1aHUwBc9svmIqso+S70uvCB7FckHx29aEPKM5Ul99KgUi43lc85Xp2DpsCYJ6u/txUPjNuzGEKwmI+QiF6qjUF9x9NRhC5pn9t1DBaljUyf+8ITog8z4uEb1ohMY8PX8fEUNJew/iZAUgPvRRiDCT6JusGu84WFAlETHGanTTxioGeSxNL4RkKGH8gjq4bNaQoLcJPeM+RBXPwpkrUJEeu47sbGmZTs5DTPp+48r64gs2D3HeAyCYDHf/pdtUKM12PsOA4y9TGQsA39WTunVe98tGEHiC+5q8gXLtFWRnyXI/bSWOpwg78TpnnKRdQ/kYuMqVQryAKC0I+rD6TlNbyGwDLMsQXbxVPnEvzq2zcdLpzM/0GQKdFXt68B69/LW94VO++5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
