appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: aDDMZYUJyys+3i868GyaVSMUPOFC2MuS5R0s/uhiEaCXKvVtQkDQIoxC+jDANY6DdgJIHtN7H3GM6DWDDutWxINWjajkiNNJ5V8P4/w9Yd0+e3iTn2vHEt/CAyfJYH5sXxLbV6qV01nZxK63+y1SNDtg3ZDkSRtn/zm0oVRYjadbWF8/AQnXBI54n+F2NZE3JVkxGjQVXcEd/T6u/FkopMpalbgkSS37MMgMdi8heVG5Pigkk4eM+4mRZ3TD2tid8T0yFM48JXcVpD0dMEIE6ypEVAruG+NoCIM+Ax7NvpW31SnPsu7SHE/8OO18hgqtUdJTBrnaemVFqlBZe1rMZ211zenfJqqtNXKyfzy3K0NKUFtQ8yVbWtNSbjZGc0sQD+ji3+R+gmDbUOPTgGKOluzeI3U68JUFdOPX4qVBeJjoXjAvXhtOTudrbcqjVhMDC87yx2vFNdM8MRTvs2HBXxMlrQpT6e8QoZC6oQzrctBWvRRX5fv5dC/o+R1BNl9sC4JB1JJpe/A/iehtTARSN16NN17E75ZXTIrpMbTJhnijEzHMTQZYbj7ZtQi9cMo5kTAcG+PiTU+Ua2MWIapyUY4WRO7lE3/txPVAI9i4+Q1uL37m6E9CzbbAdCoTyIIQHgHL87QDihuQB7vxKLfd6IXzebsBKhjU3LFTm2j4TFk=
conda_forge_output_validation: true
